environment:
  nodejs_version: "4.4"

install:
  # Install VC++ Redistributables...
  - choco install vcredist2015

  # Install the SDK.
  - MD "C:\Program Files\Tableau"
  - MD "C:\Program Files\Tableau\SDK"
  - curl -fsS -o "C:\Program Files\Tableau\sdk.zip" https://downloads.tableau.com/tssoftware/Tableau-SDK-C-Java-64Bit-9-3-0.zip
  - 7z x "C:\Program Files\Tableau\sdk.zip" -o"C:\Program Files\Tableau\SDK" -r

  # Install the node module for the targeted node version.
  - ps: Install-Product node $env:nodejs_version
  - npm -g install npm@next
  - npm install

test_script:
  - npm test

build: off
